/**
 * The SCM-agnostic publish orchestration (AUTOPILOT_PUBLISH_VIA_GIT_PROVIDER) — the claim-path analog
 * of the buildXPublishOps + compilePublishOps flow in AutopilotProvider.finalize. Given a builder's
 * held files + the user-confirmed destination, it builds a gated BuilderPublish claim (one POST op)
 * and the host-aware "Open change request" deep link (Option A). Kept out of finalize so the
 * finalize edit is a thin flag-gated delegation and the logic stays unit-testable.
 */

import type { Config } from '../../context/ConfigContext'

import type { ApplyResourceSetOp } from './applyResourceSet'
import type { AuthorshipOrigin } from './authorship'
import {
  buildBuilderPublishClaim,
  buildBuilderPublishOps,
  changeRequestDeepLink,
  resolveStructuredTarget,
  type BuilderKind,
  type BuilderPublishFile,
} from './builderPublishClaim'
import { BUILDER_PUBLISH_GVR_DENIAL, resolveBuilderPublishGvr } from './builderPublishGvr'
import type { PublishFollowSeed } from './builderPublishStore'
import { compileClaimPublish, type GateVerdict, type PublishCompileResult } from './publishCompile'

export interface ClaimPublishResult {
  compiled: PublishCompileResult
  /**
   * The host-aware Open-PR/MR URL — set only on a compiled (non-denied) publish.
   *
   * IT IS NO LONGER A PROMISE THAT THE CHANGE REQUEST EXISTS. A compiled claim means the POST is
   * ready, not that anything was pushed: the customer report this module was corrected for ended
   * with a user holding this link for twelve hours while all six git-provider children sat
   * `Synced: False`. The caller must hold it until `follow` (below) reports the push landed.
   */
  deepLink: string | null
  branch: string
  /**
   * The coordinates for WATCHING this claim's git-provider children after the POST is dispatched
   * (null on a denial — there is nothing to watch). See builderPublishStore.startPublishFollow.
   */
  follow: PublishFollowSeed | null
}

/**
 * Build + compile one builder's SCM-agnostic publish. `dest` is the user-confirmed destination from
 * the publish form (owner→namespace, repo, base) — it overrides the install-config target so the
 * human's choice always wins. `gate` returns the preview-gate verdict for the claim op set
 * (blueprint/page: blueprintGate, which now arms on `builderpublishes`; controller: the KOG gate via
 * a synthetic probe). The install-level git connection + credentials are NOT here — the composition
 * supplies them, so a token never rides in the claim.
 */
export const buildClaimPublish = async (args: {
  builder: BuilderKind
  slug: string
  files: BuilderPublishFile[]
  dest: { owner?: string; repo?: string; base?: string } | null
  namespace: string
  config: Config | undefined
  gate: (ops: ApplyResourceSetOp[]) => GateVerdict
  origin: AuthorshipOrigin
}): Promise<ClaimPublishResult> => {
  const resolved = resolveStructuredTarget(args.builder, args.config)
  const target = {
    ...resolved,
    ...(args.dest?.owner ? { namespace: args.dest.owner } : {}),
    ...(args.dest?.repo ? { repo: args.dest.repo } : {}),
    ...(args.dest?.base ? { base: args.dest.base } : {}),
  }
  // No hardcoded fallback repo: if neither install config (AUTOPILOT_<X>_BUILDER_REPO) nor the
  // human-confirmed destination supplied an owner + repo, DENY rather than POST a half-addressed
  // publish. The publish form's required fields normally guarantee both; this is defense in depth.
  if (!target.namespace || !target.repo) {
    return {
      branch: `builder/${args.slug}`,
      compiled: { denial: `denied — no publish destination: set AUTOPILOT_${args.builder === 'controller' ? 'KOG' : args.builder.toUpperCase()}_BUILDER_REPO or enter an owner/repo in the publish form.`, ops: null },
      deepLink: null,
      follow: null,
    }
  }
  // The BuilderPublish GVR is generated by core-provider (group + chart-derived version) — resolve
  // the LIVE value; a null resolution (composition absent / not ready) DENIES rather than POSTing to
  // a wrong GVR that would 404.
  const gvr = await resolveBuilderPublishGvr(args.config)
  if (!gvr) {
    return { branch: `builder/${args.slug}`, compiled: { denial: BUILDER_PUBLISH_GVR_DENIAL, ops: null }, deepLink: null, follow: null }
  }
  const claim = buildBuilderPublishClaim({ apiVersion: gvr.apiVersion, builder: args.builder, files: args.files, namespace: args.namespace, slug: args.slug, target })
  const ops = buildBuilderPublishOps(claim, gvr.gvr)
  const compiled = compileClaimPublish(ops, args.gate(ops), args.origin)
  const deepLink = compiled.denial === null ? changeRequestDeepLink(target, claim.spec.branch) : null
  return {
    branch: claim.spec.branch,
    compiled,
    deepLink,
    // The follow seed: the claim's identity plus the file count, which is the MINIMUM number of
    // git-provider LocalResources the composition must render (one per committed file). The
    // caller starts the follow only after the human confirms and the POST is actually dispatched.
    follow: deepLink === null ? null : {
      branch: claim.spec.branch,
      claimName: claim.metadata.name,
      deepLink,
      destination: `${target.namespace}/${target.repo}`,
      expectedChildren: args.files.length,
      namespace: claim.metadata.namespace,
    },
  }
}
